app:
    resource: '@AppBundle/Controller/'
    type: annotation

user_showAll:
    path:     api/v1/user
    defaults: { _controller: AppBundle:User:showAll }
    methods:  [GET] 

user_show:
    path:     api/v1/user/{id}
    defaults: { _controller: AppBundle:User:show }
    methods:  [GET] 

user_delete:
    path:     api/v1/user/{id}
    defaults: { _controller: AppBundle:User:delete }
    methods:  [DELETE]

user_create:
    path:     api/v1/user
    defaults: { _controller: AppBundle:User:new }
    methods:  [POST]              

user_edit:
    path:     api/v1/user/{id}
    defaults: { _controller: AppBundle:User:edit }
    methods:  [PUT]              

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc